"""add range and interval to ohlcv

Revision ID: 237fb043d72e
Revises: 263772f4d026
Create Date: 2026-06-21 19:16:14.810768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237fb043d72e'
down_revision: Union[str, Sequence[str], None] = '263772f4d026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohlcv', sa.Column('range', sa.String(length=10), server_default='1y', nullable=False))
    op.add_column('ohlcv', sa.Column('interval', sa.String(length=10), server_default='1d', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ohlcv', 'interval')
    op.drop_column('ohlcv', 'range')
    # ### end Alembic commands ###
