"""schema inicial

Revision ID: ec6072f37840
Revises: 
Create Date: 2026-06-18 12:00:12.490969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6072f37840'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('cache_entries',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('policy', sa.String(length=50), nullable=False),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividends_ticker'), 'dividends', ['ticker'], unique=False)
    op.create_table('ohlcv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ohlcv_ticker'), 'ohlcv', ['ticker'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change', sa.Float(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=False),
    sa.Column('day_high', sa.Float(), nullable=False),
    sa.Column('day_low', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('previous_close', sa.Float(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_ticker'), 'quotes', ['ticker'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_table('watchlists')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quotes_ticker'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_ohlcv_ticker'), table_name='ohlcv')
    op.drop_table('ohlcv')
    op.drop_index(op.f('ix_dividends_ticker'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_table('cache_entries')
    op.drop_table('assets')
    # ### end Alembic commands ###
